name: Test

on:
  # Trigger the workflow on push
  # but only for the master branch
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
    - name: Update Bundles
      run: bundle install
    - name: Run Unit Tests
      run: bundle exec fastlane custom_lane 
