name: Test

on:
  # Trigger the workflow on push
  # but only for the master branch
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Update Bundles
      run: bundle install
    - name: Run Unit Tests
      run: bundle exec fastlane custom_lane 
